web_store/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreateView, DetailsView

urlpatterns = {
    url(r'^game_json/$', CreateView.as_view(), name="create"),
    url(r'^game_json/(?P<pk>[0-9]+)/$', DetailsView.as_view(), name="details"),
}

urlpatterns = format_suffix_patterns(urlpatterns)

web_store/playing_area/urls.py
from django.conf.urls import url
from . import views

app_name = 'playing_area'

urlpatterns=[
    # our homepage
    url(r'^$', views.my_index, name='index'),
    # link to list of games
    url(r'^gameslist/$', views.my_gameslist, name='gameslist'),
    # links to games filtered by their genre
    url(r'^gameslist/[a-zA-Z0-9]+\S*/$', views.my_gameslist, name='gameslist'),
    # link to play a game
    url(r'^playgame/[a-zA-Z0-9]+\S*/$', views.playing_game, name='playgame'),
]

web_store/purchase/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^owned_game/$', views.owned_game, name='owned_game'),
    url(r'^shopping_cart/$', views.shopping_cart, name='shopping_cart'),
    url(r'^order/$', views.order, name='order'),
    url(r'^order_details/(?P<order_id>[a-zA-Z0-9]+)/$', views.order_details, name='order_details'),
    url(r'^payment_result/$', views.payment_result, name='payment_result'),
    url(r'^finish_payment/$', views.finish_payment, name='finish_payment'),
]

web_store/web_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
"""web_store URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('playing_area.urls')),
    url(r'^accounts/', include('authentication.urls')),
    url(r'^purchase/', include('purchase.urls')),
    url(r'^', include('api.urls')),
]

web_store/purchase/models.py
from django.db import models
from django.utils.timezone import now
from playing_area.models import Game
from django.contrib.auth.models import User
from authentication.models import Profile
from datetime import datetime


#creating the date of the
def get_default_ymd():
    return now().date().strftime("%Y%m%d")

#creating table of order
class Order(models.Model):
    id=models.AutoField(primary_key=True)
    _player = models.ForeignKey(Profile, null=False)
    _games = models.ManyToManyField(Game, default=None, blank=True)
    total = models.FloatField(default=0, null=False)

    orderDate = models.DateTimeField(default=datetime.now, null=False)
    orderDateYearMonthDay = models.CharField(max_length=8, default=get_default_ymd, null=False)

    paymentDate = models.DateTimeField(default=datetime.now, null=True)
    paymentRef = models.IntegerField(null=True, default=0)
    status = models.CharField(max_length=10, null=False, default="pending")

    def __str__(self):
        return str(self.total)

web_store/purchase/forms.py
from django import forms
from playing_area.models import Game


# validating the form for the shopping cart
class shoppingCartForm(forms.Form):
    action = forms.ChoiceField(choices=[('add', 'Add'), ('remove', 'Remove')], required=True)
    game = forms.ModelChoiceField(required=True, queryset=None)

    def __init__(self, *args, **kwargs):
        super(shoppingCartForm, self).__init__(*args, **kwargs)
        self.fields['game'].queryset = Game.objects.all()

web_store/purchase/views.py
from django.http.response import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse
from .forms import shoppingCartForm
from playing_area.models import Game
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from datetime import datetime
from .models import Order
from authentication.models import Profile
from django.contrib.auth.decorators import login_required
from hashlib import md5
from django.shortcuts import redirect

#shows list of owned games
@login_required
def owned_game(request):
    games = [x.add_to_json(request.user) for x in request.user.profile.ownedGames.all()]
    return render(request, 'purchase/ownedGame.html', {'user': request.user, 'games': games})


@login_required
def shopping_cart(request):

    #user validation
    try:
        Profile.objects.get(user_id=request.user.id )
    except:
        return redirect('/accounts/login')


    #checks if the request is GET, it adds the game to the session
    if request.method == 'GET':
        game_ids = request.session.get('shopping_cart_items', [])
        return render(request, 'purchase/shopping_cart.html', {'user': request.user, 'cart': add_to_cart(game_ids)})

    #checks if the request is POST, it performs some validation
    elif request.method == 'POST':
        if not request.is_ajax():
            messages.error(request, "The page that you are requesting is only available through ajax call")
            return HttpResponseRedirect(reverse("shopping_cart"))

        jscontainer = {'error': None}

        #validation based on shopping cart form
        form = shoppingCartForm(request.POST)
        if not form.is_valid():
            jscontainer['error'] = form.errors
            return JsonResponse(status=400, data=jscontainer)

        # checks if the game had been bought before or not
        if form.cleaned_data['action'] == 'add':
            owned_games = request.user.profile.ownedGames.filter(id__exact=form.cleaned_data['game'].id)
            if owned_games.count() > 0:
                jscontainer['error'] = "You already own this game"

            curcart = request.session.get('shopping_cart_items', [])

            #checks if the current session has specified game or not
            if form.cleaned_data['game'].id in curcart:
                jscontainer['error'] = "The game is already in your basket"

            if jscontainer['error'] is None:
                curcart.append(form.cleaned_data['game'].id)
                request.session['shopping_cart_items'] = curcart

        elif form.cleaned_data['action'] == 'remove':
            items = request.session.get('shopping_cart_items', [])
            if form.cleaned_data['game'].id in items:
                items.remove(form.cleaned_data['game'].id)
                request.session['shopping_cart_items'] = items

        else:
            jscontainer['error'] = "Action requested is not valid"

        if jscontainer['error'] is not None:
            return JsonResponse(status=400, data=jscontainer)
        else:
            return JsonResponse(status=201, data=jscontainer)

    else:
        return HttpResponse(status=405, content="Invalid method.")


#it gets the specified game form the databse and returns the result in order to add to the cart
def add_to_cart(game_ids,user=None):
    result = dict()
    result['games'] = list()
    result['total'] = 0
    result['quantity'] = 0
    for id in game_ids:
        try:
            game = Game.objects.get(id=id)
            result['games'].append(game.add_to_json(user=user))
            result['total'] += game.price
            result['quantity'] += 1
        except ObjectDoesNotExist:
            messages.error("one item was invalid, please check the game again!")
            continue
    return result


@login_required
def order(request):

    if request.method == 'GET':
        orders = Order.objects.filter(_player=request.user.profile)

        return render(request, 'purchase/order.html', {'orders': orders})
    #collects the games and their info from session
    elif request.method == 'POST':
        game_ids = request.session.get('shopping_cart_items', [])
        total = 0.0
        games = Game.objects.filter(id__in=game_ids)
        #check weather the user has bought the game already or not
        for game in games:
            if request.user.profile.ownedGames.filter(id__exact=game.id).count() > 0:
                messages.error(request, "You already own the game %s. This item has been removed from the cart"
                               % game.name)
                game_ids.remove(game.id)
            else:
                total += game.price

        #if status of the the order is pending, delete it
        Order.objects.filter(_player=request.user.profile, status="pending").delete()

        games = Game.objects.filter(id__in=game_ids)

        if games.count() < 1:
            messages.warning(request, "The cart is empty!")
            return HttpResponseRedirect(reverse("shopping_cart"))

        #creat the order rows in the databse
        order_obj = Order.objects.create(_player=request.user.profile,
                                     total=total,
                                     orderDate=datetime.now(),
                                     paymentDate=None,
                                     paymentRef=None,
                                     status="pending")
        order_obj._games = games.all()
        order_obj.save()

        messages.info(request, "Order created successfully.")

        return HttpResponseRedirect(reverse("order_details", kwargs={'order_id':order_obj.id}))

    else:
        return HttpResponse(status=405, content="Invalid method.")


@login_required
def order_details(request, order_id):
    if request.method == 'GET':
        if order_id is None:
            messages.error(request, "Invalid or missing Pid specified.")
            return HttpResponseRedirect(reverse("shopping_cart"))

        pid = order_id
        order = None

        #validation for user and games and order
        try:
            order = Order.objects.get(id=pid)
        except ObjectDoesNotExist:
            messages.error(request, "Invalid or missing Pid specified.")
            return HttpResponseRedirect(reverse("shopping_cart"))

        if order._player != request.user.profile:
            messages.error(request, "You are not allowed to manage this order")
            return HttpResponseRedirect(reverse("shopping_cart"))

        if order.status != "pending" and order.status != "error":
            messages.error(request, "The specified order is not on a valid status to be processed again.")
            return HttpResponseRedirect(reverse("shopping_cart"))

        #validation with payment service
        action = "https://simplepayments.herokuapp.com/pay/"
        amount = order.total
        sid = "unchained"
        success_url = request.build_absolute_uri(reverse("payment_result"))
        cancel_url = request.build_absolute_uri(reverse("payment_result"))
        error_url = request.build_absolute_uri(reverse("payment_result"))
        secret_key = "9a4b9b18721dc20344dba2bd26b737e3"

        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum = m.hexdigest()

        game_ids = [g.id for g in order._games.all()]

        #assigning the validated data to the buying.html form attribute
        return render(request, 'purchase/buying.html', {'user': request.user,
                                                       'cart':  add_to_cart(game_ids),
                                                       'action': action,
                                                       'pid': pid,
                                                       'sid': sid,
                                                       'amount': amount,
                                                       'success_url': success_url,
                                                       'cancel_url': cancel_url,
                                                       'error_url': error_url,
                                                       'checksum': checksum})

    else:
        return HttpResponse(status=405, content="Invalid method.")


@login_required
def payment_result(request):
    if request.method == 'GET':
        pid = request.GET['pid']
        ref = request.GET['ref']
        result = request.GET['result']
        checksum = request.GET['checksum']

        #checking wether the information from payment service is validated
        sid = "unchained"
        secret_key = "9a4b9b18721dc20344dba2bd26b737e3"
        checksumstr = "pid={}&ref={}&result={}&token={}".format(pid, ref, result, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum2 = m.hexdigest()

        if checksum != checksum2:
            messages.error(request, "Invalid checksum. Your payment is invalid.")
            return HttpResponseRedirect(redirect_to=reverse("shopping_cart"))


        order = None
        try:
            order = Order.objects.get(id=pid)
        except ObjectDoesNotExist:
            messages.error(request, "Invalid OrderId specified. Your payment is invalid.")
            return HttpResponseRedirect(redirect_to=reverse("shopping_cart"))

        if order._player != request.user.profile:
            messages.error(request, "The order ID specified is not yours. Your payment is invalid.")
            return HttpResponseRedirect(redirect_to=reverse("shopping_cart"))

        if order.status != "pending":
            messages.error(request, "The order ID specified is not in the pending status. Please make another order.")
            return HttpResponseRedirect(redirect_to=reverse("shopping_cart"))

        if result not in ["success", "cancel", "error"]:

web_store/purchase/templates/purchase/buying.html
{% extends 'playing_area/base.html' %}
{% block title %}Your Order{% endblock %}
{% load staticfiles %}
{% block body %}
    <link rel="stylesheet" href="{% static "purchase/ownedGame.css" %}">
    <div class="container">
       <h1 class="text-center">Your Order</h1>
           <hr style="margin-bottom:35px; width:100%; border: 0; height: 1px; background: #333; background-image: linear-gradient(to right, #ccc, #333, #ccc);">

        {% for i in cart.games %}

            <ul><div id="div-{{ i.id }}" class="divSpace">
                <div class="purchaseDiv">
                    <p class="lead gameName">{{ forloop.counter }}. {{ i.name }} <span class="purchasePrice"><script type="text/javascript">document.write(formatPrice("{{ i.price }}"));</script></span></p>
                </div>
            </div>
         <hr style="width: 50%;text-align:left;  margin-left:0;height: 0; border-top: 1px solid rgba(0, 0, 0, 0.1);border-bottom: 1px solid rgba(255, 255, 255, 0.3);">
            </ul>
        {% endfor %}
        <form action="{{ action }}" method="POST" id="purchaseForm">
            <input type="hidden" name="pid" value="{{ pid }}" />
            <input type="hidden" name="sid" value="{{ sid }}" />
            <input type="hidden" name="success_url"
                    value="{{ success_url }}" />
            <input type="hidden" name="cancel_url"
                    value="{{ cancel_url }}" />
            <input type="hidden" name="error_url"
                    value="{{ error_url }}" />
            <input type="hidden" name="checksum"
                    value="{{ checksum }}" />

            <ul><input type="text" id="id_amount" name="amount" value="{{ amount }}"/>
            <label for="id_amount" class="alignRight">&#36;  Total Amount</label></ul>
            <br/>
            <br/>

            <div class="row">
                <div class="col-md-3 col-xs-12">
                    <a href="{% url 'shopping_cart' %}"><button type="button" class="btn btn-primary btn-block"><span class="fa fa-angle-left"></span>
                    Continue Shopping
                    </button></a>
                </div>
                <div class="col-md-3 col-xs-12">
                    <input type="submit" class="btn btn-success btn-block" value="Pay!"/>
                </div>
            </div>
        </form>


    </div>

</div>
{% endblock %}

web_store/purchase/templates/purchase/ownedGame.html
{% extends 'playing_area/base.html' %}
{% block title %}Owned Game{% endblock %}
{% load staticfiles %}
{% block body %}

<link rel="stylesheet" href="{% static "purchase/ownedGame.css" %}">
<div class="container">
    <h1 class="text-center">My Games</h1>
        <hr style="margin-bottom:35px; width:100%; border: 0; height: 1px; background: #333; background-image: linear-gradient(to right, #ccc, #333, #ccc);">

       {% for game in games %}
    <div class="col-ms-10 col-md-4" >
        <div class="project">
            <figure class="img-responsive" >
                    {% if game.image_url != '' %}
                        <img src="{{ game.image_url }}" class="img-game img-responsive"
                             alt="Image Not Found">
                    {% endif %}
                    {% if game.image_url == '' %}
                        <img src="{% static "playing_area/images/no_image.png" %}"
                             class="img-game gameimg-responsive"
                             >
                    {% endif %}

                <figcaption>

                    <span class="project-details"><a href="/playgame/{{ game.name }}"><strong>{{ game.name }}</strong></a></span>

                </figcaption>

                <span class="actions">
                        <a href="/playgame/{{ game.name }}"><button class="btn btn-warning bnt-action" type="submit"  >View </button></a>
                </span>

            </figure>

        </div>
    </div>
    {% endfor %}
</div>



{% endblock %}

web_store/purchase/templates/purchase/shopping_cart.html
{% extends 'playing_area/base.html' %}
{% block title %}Shopping Cart{% endblock %}
{% load staticfiles %}
{% block body %}


    <div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-12">
								<h4><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h4>
							</div>

						</div>
					</div>
				</div>
				<div class="panel-body">
                    {% for item in cart.games %}
					<div class="row" id="div-{{ item.id }}">
						<div class="col-xs-2"><img class="img-responsive hidden-xs" alt="No image available." style="height: 70px; width: 130px;" src="{{ item.image_url }}">
						</div>
						<div class="col-xs-4">
							<h4 class="product-name"><strong>{{ item.name }}</strong></h4><h4><small>Genre: {{ item.genre }}</small></h4>
						</div>
						<div class="col-xs-6">
							<div class="col-xs-6 text-right">
								<h6><strong>${{ item.price }}</strong></h6>
							</div>
							<div class="col-xs-6 text-right">
								<button type="button" class="btn btn-danger " onclick="removeItem({{ item.id }})">
                                    <span class="glyphicon glyphicon-trash" ></span>
                                </button>
							</div>
						</div>
					</div>
					<hr>
                    {% endfor %}

                    <div class="row">
                        <div class="text-center">
							<div class="col-xs-9">
								<h4 class="text-right">Quantity: <strong>{{ cart.quantity }}</strong></h4>
							</div>
							<div class="col-xs-3">
								<h4 class="text-center">Total: <strong>${{ cart.total }}</strong></h4>
							</div>
						</div>
                    </div>

				</div>
				<div class="panel-footer">
					<div class="row">
                        <div class="col-md-3 col-xs-12">
								<form action="{% url 'playing_area:index' %}" method="POST">
                                 {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-block"><span class="fa fa-angle-left"></span>
                            Continue Shopping
                            </button>
                            </form>
							</div>{% if cart.quantity > 0 %}
						    <div class="col-md-2 col-md-offset-7 col-xs-12">
                                <form action="{% url 'order' %}" method="POST">
                                     {% csrf_token %}
                                <button type="submit" class="btn btn-success btn-block">
                                Checkout <span class="fa fa-angle-right"></span>
                                </button>
                                </form>
						    </div>
                        {% else %}
                            <div class="col-md-2 col-md-offset-7 col-xs-12 text-center">
                            <h4 class="text-danger">Your cart is empty!</h4>
                         </div>
                    {% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




     <script type="text/javascript">

             function removeItem(gameid) {
            $.ajax({
                method:'POST',
                url: "{% url 'shopping_cart' %}",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token  }}",
                    game:gameid,
                    action:'remove'
                },
                success:function(data) {
                    if (data.error) {
                        alert("Error: " + data.error);
                    }
                    else{
                        $('#div-'+gameid).fadeOut(280,function(){this.remove()});
                        location.reload();
                    }
                },
                error: function (data) {
                    if (data.error) {
                        alert("There was a problem during the request. Please try again.");
                    }
                }
            })
        }

     </script>

{% endblock %}